#!/usr/bin/env bash
set -euo pipefail

DDB_LOCAL='http://localhost:25002'

aws dynamodb create-table \
	--endpoint-url $DDB_LOCAL \
	--table-name 'uxrp-auth' \
	--attribute-definitions 'AttributeName=id,AttributeType=S' \
	--key-schema 'AttributeName=id,KeyType=HASH' \
	--billing-mode 'PAY_PER_REQUEST'
