#!/usr/bin/env bash
set -euo pipefail

BASE_URL='http://localhost:1337'
CURL_OPTS=( -H 'content-type: application/json' )

echo 'registering'

curl $BASE_URL/auth/register "${CURL_OPTS[@]}" \
	-d '{"email": "ruan@test.test", "password": "test"}' || true

echo 'logging in'

curl $BASE_URL/auth/login "${CURL_OPTS[@]}" \
	-d '{"email": "ruan@test.test", "password": "test"}'
