name: Commit

on: push

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-20.04
        toolchain:
        - 1.57.0

    runs-on: ${{ matrix.os }}

    env:
      AWS_DEFAULT_REGION: eu-west-1
      AWS_ACCESS_KEY_ID: blah
      AWS_SECRET_ACCESS_KEY: blah

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        components: rustfmt, clippy
        toolchain: ${{ matrix.toolchain }}

    - name: Boot test dependencies
      run: docker-compose up -d && ./bootstrap
    
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test

    - name: Run clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings
